### ISSUE TITLE
Transpiled version?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [underscopeio/react-native-facebook-account-kit#48]
This module works great in our devices and simulators.

But it fails our mocha tests with the following error:
```bash
return RNAccountKitNative.configure(configOptions);
TypeError: Cannot read property 'configure' of undefined
    at RNAccountKit.configure (/Users/giro/stardust-app/node_modules/react-native-facebook-account-kit/index.js:41:12)
```

This seems to be happening when Babel tries to import this module, since it's not already transpiled like most modules, from what I can tell.

According to http://stackoverflow.com/questions/35040978/babel-unexpected-token-import-when-running-mocha-tests, all distributed modules should be transpiled already-- is this something we can do for this module?

**Comment by GeoffreyPlitt** [comment]
Follow-up: We've definitely done all of the "react-native link" (equivalent to rnpm link) stuff correctly. If we hadn't, it wouldn't work in simulators/devices-- and it works fine in both android/ios simulators and devices.

So this issue is specific to mocha tests, and specific to the Babel integration, transpiling, etc.

**Comment by gaguirre** [comment]
Thanks for submitting a new issue @GeoffreyPlitt 
I'll take a look on this days! Please post any update you have on this ;)

**Comment by GeoffreyPlitt** [comment]
Thanks! Here's something new: I suspect the solution might be to make sure this module is compile-able with the "react-native" Babel preset, see https://github.com/facebook/react-native/tree/master/babel-preset

**Comment by GeoffreyPlitt** [comment]
More context: This doesn't involve either Android or iOS. We're using the framework from https://github.com/futurice/pepperoni-app-kit#testing-setup, and https://github.com/lelandrichardson/react-native-mock so that the Mocha tests can run on the RN codebase without actually touching Android/iOS stuff.

**Comment by DrJid** [comment]
I'm seeing this on a fresh react-native project built with 'react-native init MyProject', then npm installed account kit and linked using. 

npm install --save react-native-facebook-account-kit
react-native link react-native-facebook-account-kit

As soon as I add the import lines, 

import AccountKit, {
  Color,
  StatusBarStyle,
} from 'react-native-facebook-account-kit'

It shows the exact same error. So I don't think it's confied to just the mocha testing..

**Comment by GeoffreyPlitt** [comment]
I got a notification about this comment, but it seemed to have dissapeared, and yet is relevant. Yesteray, Maijid Moujaled said:

I'm seeing this on a fresh react-native project built with 'react-native init MyProject', then npm installed account kit and linked using.

npm install --save react-native-facebook-account-kit
react-native link react-native-facebook-account-kit

As soon as I add the import lines,

import AccountKit, {
Color,
StatusBarStyle,
} from 'react-native-facebook-account-kit'

It shows the exact same error. So I don't think it's confied to just the mocha testing..

**Comment by GeoffreyPlitt** [comment]
@gaguirre Do you think you can look at this soon?

**Comment by gaguirre** [comment]
Hi @GeoffreyPlitt, I can't right now. Maybe I can take a look tonight.
Would you like to send a PR? It would be great if you could!

**Comment by GeoffreyPlitt** [comment]
@gaguirre I would love to! But I don't know how. The error message showing is NOT enough to solve the problem. This one needs native android expertise from the person who wrote the module. 

I time this week, so if you can tell me how to fix it, I can send a PR.

Again, need help because the error message is frustratingly giving no indication of what the bad JSON is, or what in JS land triggered this.

===> Can any other module authors help?

**Comment by gaguirre** [comment]
I figured out what's happening (I hope).
Our module creates an instance of `RNAccountKit` class and its constructor is calling to a `NativeModules.RNAccountKit` method, which is not defined at all. So this will crash when requiring `react-native-facebook-account-kit`.

Let me do a quick fix and try it again! I'll let you know ;)

**Comment by gaguirre** [comment]
@GeoffreyPlitt would you mind to try the (hopefully) fix I just pushed to the **fix/48** branch?
 
To do that replace in your **package.json** this line
```
"react-native-facebook-account-kit": "git@github.com:underscopeio/react-native-facebook-account-kit.git#fix/48"
```
then run `npm install` and finally run the tests again.

Thanks! I'll wait to your answer :)

**Comment by GeoffreyPlitt** [comment]
Sorry for the late replace, but that seems to have fixed it! Merge away, thanks.

**Comment by yapitsmalvinder** [comment]
Hi @gaguirre
Still facing the same issue
wasted complete day on the same

**Comment by gaguirre** [comment]
Hi @yapitsmalvinder,
Which error are you facing exactly? This issue was fixed from version **0.5.2**

**Comment by yapitsmalvinder** [comment]
I am importing
I am using ver: 0.9.0

import AccountKit, { Color, StatusBarStyle } from 'react-native-facebook-account-kit';

Whenever I do 
AccountKit.configure()
or any other method
like:
AccountKit.getCurrentAccount()

It says
TypeError: cannot read property 'getCurrentAccesToken' of undefined
[
![simulator screen shot - iphone 6 - 2017-12-06 at 19 09 57](https://user-images.githubusercontent.com/32063937/33664328-3a4c07fe-dab9-11e7-971b-6b8b305dd31f.png)
](url)

**Comment by gaguirre** [comment]
Probably the module is not correctly linked. 
Try re-installing this module. Follow the [Installation](https://github.com/underscopeio/react-native-facebook-account-kit#installation) and [Configuration](https://github.com/underscopeio/react-native-facebook-account-kit#configuration) steps.

**Comment by yapitsmalvinder** [comment]
@gaguirre 
Followed all the processes thoroughly
4 times
tried different projects to do the same
Still the same issue:

react: 16.0.0
react-native: 0.50.4
react-native-facebook-account-kit: 0.9.0
